function pos = leg_pos_1(phi1,phi4)
%LEG_POS_1
%    POS = LEG_POS_1(PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-04-15 22:39:55

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = t2.*(3.0./2.0e+1);
t7 = t3.*(3.0./2.0e+1);
t8 = t2.*(3.0./4.0e+1);
t9 = t3.*(3.0./4.0e+1);
t10 = t4.*(3.0./2.0e+1);
t11 = t5.*(3.0./2.0e+1);
t12 = t4.*(3.0./4.0e+1);
t13 = t5.*(3.0./4.0e+1);
t14 = -t6;
t15 = -t8;
t16 = -t11;
t17 = -t12;
t18 = -t13;
t19 = t10+t16;
t20 = t12+t18;
t23 = t7+t14+3.0./2.0e+1;
t24 = t9+t15+3.0./4.0e+1;
t21 = t19.^2;
t22 = t20.^2;
t25 = t23.^2;
t26 = t24.^2;
t27 = t21+t25;
t28 = t27.^2;
t30 = t24+t27;
t29 = -t28;
t31 = 1.0./t30;
t32 = t22+t26+t29;
t33 = sqrt(t32);
t34 = t13+t17+t33;
t35 = t31.*t34;
t36 = atan(t35);
t37 = t36.*2.0;
t38 = cos(t37);
t39 = sin(t37);
t40 = t38./4.0;
pos = [sqrt((t10+t39./4.0).^2+(t6+t40-3.0./4.0e+1).^2);atan2(t4.*(3.0./2.0e+1)+t39./4.0,t6+t40-3.0./4.0e+1)];
end
