/*
 * File: leg_spd_1.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 05-Nov-2024 23:08:18
 */

/* Include Files */
#include "leg_spd_1.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_SPD_1
 *     SPD = LEG_SPD_1(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : double dphi1
 *                double dphi4
 *                double phi1
 *                double phi4
 *                double spd[2]
 * Return Type  : void
 */
void leg_spd_1(float dphi1, float dphi4, float phi1, float phi4,
               float spd[2])
{
  double t106;
  double t10_tmp;
  double t11;
  double t12;
  double t13;
  double t14_tmp;
  double t15;
  double t16;
  double t17;
  double t2;
  double t28;
  double t29;
  double t3;
  double t32;
  double t33;
  double t4;
  double t44;
  double t47;
  double t5;
  double t56;
  double t70;
  double t71;
  double t76;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-10-18 21:47:26 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t10_tmp = t2 * 0.15;
  t11 = t3 * 0.15;
  t12 = t2 * 0.075;
  t13 = t3 * 0.075;
  t14_tmp = t4 * 0.15;
  t15 = t5 * 0.15;
  t16 = t4 * 0.075;
  t17 = t5 * 0.075;
  t28 = t14_tmp - t15;
  t29 = t16 - t17;
  t32 = (t11 - t10_tmp) + 0.15;
  t33 = (t13 - t12) + 0.075;
  t44 = t28 * t28 + t32 * t32;
  t47 = t2 * t28 * 0.3 + t4 * t32 * 0.3;
  t3 = t3 * t28 * 0.3 + t5 * t32 * 0.3;
  t28 = 1.0 / (t33 + t44);
  t32 = t28 * t28;
  t5 = sqrt((t29 * t29 + t33 * t33) - t44 * t44);
  t56 = 1.0 / t5;
  t4 = (t17 - t16) + t5;
  t2 = atan(t28 * t4) * 2.0;
  t70 = cos(t2);
  t71 = sin(t2);
  t76 = 1.0 / (t32 * (t4 * t4) + 1.0);
  t106 =
      (t16 + t47) * t32 * t4 +
      t28 * (t12 -
             t56 * ((t10_tmp * t29 + t14_tmp * t33) - t44 * t47 * 2.0) / 2.0);
  t2 = (t17 + t3) * t32 * t4 +
       t28 * (t13 - t56 * ((t11 * t29 + t15 * t33) - t44 * t3 * 2.0) / 2.0);
  t12 = t14_tmp + t71 / 4.0;
  t16 = (t10_tmp + t70 / 4.0) - 0.075;
  t5 = t70 * t76;
  t11 = t5 * t2;
  t32 = t71 * t76;
  t47 = t32 * t2;
  t2 = (-t10_tmp - t70 / 4.0) + 0.075;
  t56 = t2 * t2;
  t28 = 1.0 / t2;
  t4 = t12 * t12;
  t2 = 1.0 / sqrt(t4 + t16 * t16);
  t3 = 1.0 / (t4 + t56);
  t5 = t10_tmp - t5 * t106 / 2.0;
  t4 = t14_tmp - t32 * t106 / 2.0;
  spd[0] = dphi4 * t2 * (t12 * t11 - t16 * t47) / 2.0 +
           dphi1 * t2 * (t12 * t5 * 2.0 - t16 * t4 * 2.0) / 2.0;
  t2 = t12 * (1.0 / t56);
  spd[1] = -dphi1 * t56 * t3 * (t28 * t5 - t2 * t4) +
           dphi4 * t56 * t3 * (t28 * (0.0 - t11 / 2.0) + t2 * (t47 / 2.0));
}

/*
 * File trailer for leg_spd_1.c
 *
 * [EOF]
 */
