/*
 * File: leg_conv_1.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 03-Nov-2024 20:51:48
 */

/* Include Files */
#include "leg_conv_1.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV_1
 *     T = LEG_CONV_1(F,Tp,PHI1,PHI4)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi4
 *                double T[2]
 * Return Type  : void
 */
void leg_conv_1(float F, float Tp, float phi1, float phi4, float T[2])
{
  double t123_tmp;
  double t124_tmp;
  double t131_tmp;
  double t16_tmp;
  double t174;
  double t175;
  double t17_tmp;
  double t180_tmp;
  double t19_tmp;
  double t20_tmp;
  double t21_tmp;
  double t23_tmp;
  double t47_tmp;
  double t48_tmp;
  double t54_tmp;
  double t55_tmp;
  double t5_tmp;
  double t6_tmp;
  double t77_tmp;
  double t7_tmp;
  double t81_tmp;
  double t96;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-10-18 21:47:27 */
  t96 = cos(phi1);
  t5_tmp = cos(phi4);
  t6_tmp = sin(phi1);
  t7_tmp = sin(phi4);
  t16_tmp = t96 * 0.15;
  t17_tmp = t5_tmp * 0.15;
  t174 = t96 * 0.075;
  t19_tmp = t5_tmp * 0.075;
  t20_tmp = t6_tmp * 0.15;
  t21_tmp = t7_tmp * 0.15;
  t175 = t6_tmp * 0.075;
  t23_tmp = t7_tmp * 0.075;
  t47_tmp = t20_tmp - t21_tmp;
  t48_tmp = t175 - t23_tmp;
  t54_tmp = (t17_tmp - t16_tmp) + 0.15;
  t55_tmp = (t19_tmp - t174) + 0.075;
  t77_tmp = t47_tmp * t47_tmp + t54_tmp * t54_tmp;
  t81_tmp = t96 * t47_tmp * 0.3 + t6_tmp * t54_tmp * 0.3;
  t5_tmp = t5_tmp * t47_tmp * 0.3 + t7_tmp * t54_tmp * 0.3;
  t7_tmp = 1.0 / (t55_tmp + t77_tmp);
  t47_tmp = t7_tmp * t7_tmp;
  t96 = sqrt((t48_tmp * t48_tmp + t55_tmp * t55_tmp) - t77_tmp * t77_tmp);
  t54_tmp = 1.0 / t96;
  t96 += t23_tmp - t175;
  t6_tmp = atan(t7_tmp * t96) * 2.0;
  t123_tmp = cos(t6_tmp);
  t124_tmp = sin(t6_tmp);
  t131_tmp = 1.0 / (t47_tmp * (t96 * t96) + 1.0);
  t180_tmp = (t175 + t81_tmp) * t47_tmp * t96 +
             t7_tmp * (t174 - t54_tmp *
                                  ((t16_tmp * t48_tmp + t20_tmp * t55_tmp) -
                                   t77_tmp * t81_tmp * 2.0) /
                                  2.0);
  t17_tmp = (t23_tmp + t5_tmp) * t47_tmp * t96 +
            t7_tmp * (t19_tmp - t54_tmp *
                                    ((t17_tmp * t48_tmp + t21_tmp * t55_tmp) -
                                     t77_tmp * t5_tmp * 2.0) /
                                    2.0);
  t19_tmp = t20_tmp + t124_tmp / 4.0;
  t21_tmp = (t16_tmp + t123_tmp / 4.0) - 0.075;
  t96 = (-t16_tmp - t123_tmp / 4.0) + 0.075;
  t174 = t96 * t96;
  t175 = 1.0 / t96;
  t6_tmp = t19_tmp * t19_tmp;
  t81_tmp = t123_tmp * t131_tmp;
  t54_tmp = t16_tmp - t81_tmp * t180_tmp / 2.0;
  t47_tmp = t124_tmp * t131_tmp;
  t5_tmp = t20_tmp - t47_tmp * t180_tmp / 2.0;
  t7_tmp = F * (1.0 / sqrt(t6_tmp + t21_tmp * t21_tmp));
  t6_tmp = Tp * t174 * (1.0 / (t6_tmp + t174));
  t96 = t19_tmp * (1.0 / t174);
  T[0] = t7_tmp * (t19_tmp * t54_tmp * 2.0 - t21_tmp * t5_tmp * 2.0) / 2.0 -
         t6_tmp * (t175 * t54_tmp - t96 * t5_tmp);
  T[1] = t7_tmp * (t81_tmp * t19_tmp * t17_tmp - t47_tmp * t21_tmp * t17_tmp) /
             2.0 +
         t6_tmp * (t175 * (0.0 - t81_tmp * t17_tmp / 2.0) +
                   t96 * (t47_tmp * t17_tmp / 2.0));
}

/*
 * File trailer for leg_conv_1.c
 *
 * [EOF]
 */
